name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Repository Structure
        run: |
          echo "Current working directory: $(pwd)"
          ls -la
          find . -type d -maxdepth 1
          echo "Checking for service directories:"
          for SERVICE in zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service; do
            if [ -d "$SERVICE" ]; then
              echo "$SERVICE exists"
            else
              echo "$SERVICE does not exist"
            fi
          done

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          SERVICES="zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service"
          for SERVICE in $SERVICES; do
            IMAGE_NAME=$(echo $SERVICE | sed 's/zyra-//')
            IMAGE_TAG="$DOCKERHUB_USERNAME/zyra-moments-$IMAGE_NAME:latest"

            echo "Processing service: $SERVICE"

            if [ -d "$SERVICE" ]; then
              if [ -f "$SERVICE/dockerfile" ]; then
                echo "Found dockerfile (lowercase) in $SERVICE"
                docker build -f $SERVICE/dockerfile -t $IMAGE_TAG $SERVICE
              elif [ -f "$SERVICE/Dockerfile" ]; then
                echo "Found Dockerfile (uppercase) in $SERVICE"
                docker build -f $SERVICE/Dockerfile -t $IMAGE_TAG $SERVICE
              else
                echo "No Dockerfile found in $SERVICE"
                exit 1
              fi

              docker push $IMAGE_TAG
            else
              echo "Directory $SERVICE not found"
              exit 1
            fi
          done

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            whoami
            echo "Current directory: $(pwd)"
            docker --version
            docker compose version

            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || { echo "Docker login failed"; exit 1; }

            cd /home/ubuntu || { echo "Directory /home/ubuntu not found"; exit 1; }

            docker compose pull || { echo "Docker compose pull failed"; exit 1; }
            docker compose up -d || { echo "Docker compose up failed"; exit 1; }
