name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    - name: Build and Push Docker Images
      run: |
        SERVICES="zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service"
        for SERVICE in $SERVICES; do
          echo "Building $SERVICE"
          docker build -t $DOCKERHUB_USERNAME/$SERVICE:latest ./$SERVICE
          docker push $DOCKERHUB_USERNAME/$SERVICE:latest
        done

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          SERVICES="zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service"
          for SERVICE in $SERVICES; do
            echo "Deploying $SERVICE"
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest
            sudo docker stop $SERVICE || true
            sudo docker rm $SERVICE || true
            sudo docker run -d --name $SERVICE ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest
          done
