name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    - name: Build and Push Docker Images
      run: |
        SERVICES="zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service"
        for SERVICE in $SERVICES; do
          docker build -t $DOCKERHUB_USERNAME/$SERVICE:latest ./$SERVICE
          docker push $DOCKERHUB_USERNAME/$SERVICE:latest
        done

    - name: Setup SSH and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          SERVICES="zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service"
          for SERVICE in $SERVICES; do
            docker pull $DOCKERHUB_USERNAME/$SERVICE:latest
            docker stop $SERVICE || true
            docker rm $SERVICE || true
            docker run -d --name $SERVICE $DOCKERHUB_USERNAME/$SERVICE:latest
          done
