name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Debug Repository Structure
      #   run: |
      #     echo "Current working directory: $(pwd)"
      #     ls -la
      #     find . -type d -maxdepth 1
      #     echo "Checking for service directories:"
      #     for SERVICE in zyra-api-gateway zyra-auth-service zyra-client-service zyra-admin-service zyra-msg-service zyra-vendor-service; do
      #       if [ -d "$SERVICE" ]; then
      #         echo "$SERVICE exists"
      #       else
      #         echo "$SERVICE does not exist"
      #       fi
      #     done

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Docker Build & Push
        run: |
          docker build -t ${DOCKERHUB_USERNAME}/zyra-moments-api-gateway .
          docker push ${DOCKERHUB_USERNAME}/zyra-moments-api-gateway

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            whoami
            echo "Current directory: $(pwd)"
            docker --version
            docker compose version

            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin || { echo "Docker login failed"; exit 1; }
            cd /home/ubuntu || { echo "Directory /home/ubuntu not found"; exit 1; }

            docker compose down || { echo "Docker compose down failed"; exit 1; }

            docker compose pull || { echo "Docker compose pull failed"; exit 1; }
            docker compose up -d || { echo "Docker compose up failed"; exit 1; }
