name: Sync Proto Submodule and Generate Stubs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual execution
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  sync-proto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Auth Service Repo
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure proto submodule is updated

      - name: Pull Latest Proto Changes
        run: |
          git submodule update --remote --merge
          git add proto/
          git commit -m "Updated proto definitions from proto-repo" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Verify .proto Files Exist
        run: ls -R proto/

      - name: Install Protobuf Compiler
        run: |
          sudo apt update && sudo apt install -y protobuf-compiler
          protoc --version

      - name: Install Go and gRPC Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Generate gRPC Stubs
        run: |
          mkdir -p generated
          protoc --proto_path=proto --go_out=generated --go-grpc_out=generated $(find proto -name "*.proto")

      - name: Upload Generated Files
        uses: actions/upload-artifact@v4
        with:
          name: grpc-stubs
          path: generated/
